---
apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: function1
spec:
  handler: hello.foobar
  runtime: python2.7
  deps: |
    cowpy
  function: |
      import time
      import random
      from cowpy import cow
      def foobar():
        # NB: delay will be negative and sleep will raise an error
        # occasionally.  This is a feature for demoing errors.
        delay = random.normalvariate(0.3, 0.2)
        time.sleep(delay)
        msg = "hello world - with a %0.2fs artificial delay" % delay
        c = cow.get_cow()
        return c().milk(msg)
