---
apiVersion: k8s.io/v1
kind: Function
metadata:
  name: function
spec:
  handler: hello.handler
  runtime: python2.7
  function: |
      import json
      def handler():
              return "hello world"
