---
apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: function
spec:
  handler: hello.handler
  runtime: nodejs6
  function: |
      module.exports = {
        hello: function(req, res) {
          res.end('Hello World')
        }
      }
