version: 2.1

## Definitions
build_allways: &build_allways
  filters:
    tags:
      only: /.*/
defaults: &defaults
  # working_directory: /home/circleci/.go_workspace/src/github.com/kubeless/nats-trigger
  environment:
    # GOPATH: /home/circleci/.go_workspace
    NATS_CONTROLLER_IMAGE_NAME: kubeless/nats-trigger-controller
    CGO_ENABLED: "0"
    TEST_DEBUG: "1"
    GKE_VERSION: 1.8.10-gke.0
    MINIKUBE_VERSION: v1.17.0
    MANIFESTS: nats
    # GO111MODULE: "on"
exports: &exports
  # It is not possible to resolve env vars in the environment section:
  # https://discuss.circleci.com/t/using-environment-variables-in-config-yml-not-working/14237
  run: |
    CONTROLLER_TAG=${CIRCLE_TAG:-build-$CIRCLE_WORKFLOW_ID}
    echo "export CONTROLLER_TAG=${CONTROLLER_TAG}" >> $BASH_ENV
    echo "export NATS_CONTROLLER_IMAGE=${NATS_CONTROLLER_IMAGE_NAME}:${CONTROLLER_TAG}" >> $BASH_ENV
    echo "export KUBECFG_JPATH=/home/circleci/src/github.com/kubeless/kubeless/ksonnet-lib" >> $BASH_ENV
    echo "export PATH=$(pwd)/bats/libexec:$PATH" >> $BASH_ENV
restore_workspace: &restore_workspace
  run: |
    make bootstrap
    sudo cp -r /tmp/go/bin/* /usr/local/bin/
    cp -r /tmp/go/src/github.com/kubeless/nats-trigger/build-manifests/*yaml .
should_test: &should_test
  run: |
    case $CIRCLE_JOB in
    # In kase of minikube+NATS we want to test it if
    # it is a Pull Request related to NATS (discovered from the PR title)
    # or if the build is from the "master" branch
    minikube_nats)
      if [[ -n "$CIRCLE_PULL_REQUESTS" ]]; then
        pr_nats_title=$(curl -H "Authorization: token $ACCESS_TOKEN" "https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/${TRAVIS_PULL_REQUEST}" | grep title || true)
      fi
      if [[ -z "$CIRCLE_PULL_REQUESTS" || "$pr_nats_title" == "" || "$pr_nats_title" =~ ^.*(Nats|nats|NATS).*$ ]]; then
        export SHOULD_TEST=1
      fi
      ;;
    esac
    echo "Should test? $SHOULD_TEST"
    if [[ "$SHOULD_TEST" != "1" ]]; then
      circleci step halt
    fi
#### End of definitions

workflows:
  version: 2
  kubeless:
    jobs:
      - build:
          <<: *build_allways
      - minikube_nats:
          <<: *build_allways
          requires:
            - build
          matrix:
            parameters:
              # Amazon EKS Kubernetes versions.
              # See https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
              k8s-version:
                - v1.19.7
      - push_latest_images:
          filters:
            branches:
              only: master
          requires:
            - minikube_nats
      - release:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
          requires:
            - minikube_nats
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - <<: *exports
      - run: make bootstrap
      - run: mkdir build-manifests
      # Install kubeless required files
      - run: |
          git clone https://github.com/kubeless/kubeless.git $GOPATH/src/github.com/kubeless/kubeless
          ln -s $(pwd)/ksonnet-lib $GOPATH/src/github.com/kubeless/kubeless/ksonnet-lib
          cd $GOPATH/src/github.com/kubeless/kubeless
          make binary
          make all-yaml
          cd -
          cp $GOPATH/src/github.com/kubeless/kubeless/kubeless-non-rbac.yaml $GOPATH/src/github.com/kubeless/kubeless/kubeless.yaml build-manifests/
      - run: make VERSION=${CONTROLLER_TAG} binary
      - run: make test
      - run: make validation
      - run: make all-yaml
      - run: |
          IFS=' ' read -r -a manifests <<< "$MANIFESTS"
          for f in "${manifests[@]}"; do
            sed -E -i.bak 's/image: .*\/nats-trigger-controller:.*/image: kubeless\/nats-trigger-controller:'"${CONTROLLER_TAG}"'/g' ${f}.yaml
            cp ${f}.yaml build-manifests/
          done
      - persist_to_workspace:
          root: /home/circleci/.go_workspace
          paths: 
            - bin
            - src/github.com/kubeless/nats-trigger/build-manifests/*yaml
      - store_artifacts:
          path: /home/circleci/.go_workspace/bin/kubeless
      - store_artifacts:
          path: build-manifests
  minikube_nats:
    <<: *defaults
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - <<: *should_test
      - checkout
      - <<: *exports
      - attach_workspace:
          at: /tmp/go
      - <<: *restore_workspace
      - run: ./script/pull-or-build-image.sh nats-controller-image
      - run: ./script/integration-tests minikube deployment
      - run: ./script/integration-tests minikube nats
  push_latest_images:
    <<: *defaults
    docker:
      - image: circleci/golang:1.15
    steps:
      - <<: *exports
      - setup_remote_docker
      - run: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"   
      - run: |
          images=( 
            $NATS_CONTROLLER_IMAGE_NAME
          )
          for image in "${images[@]}"; do
            echo "Pulling ${image}:${CONTROLLER_TAG}"
            docker pull ${image}:${CONTROLLER_TAG}
            docker tag ${image}:${CONTROLLER_TAG} ${image}:latest
            docker push ${image}:latest
          done
  release:
    <<: *defaults
    docker:
      - image: circleci/golang:1.15
    steps:
      - <<: *exports
      - checkout
      - attach_workspace:
          at: /tmp/go
      - <<: *restore_workspace
      - run: ./script/create_release.sh ${CIRCLE_TAG} "${MANIFESTS}"
