apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  labels:
    kubeless: kafka
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: kubeless-kafka
    fsType: ext4

