apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
  labels:
    kubeless: zookeeper
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: kubeless-zookeeper
    fsType: ext4

